### PR TITLE
Upgrade gradle and support 2021.3

### PR DESCRIPTION
**Pull request by gaborbernat**
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>

### CODE REVIEW

**Comment by andrask** [comment]
Hi Gabor! Thanks a lot for the commit. It looks like we have to do this change for all new versions but the used APIs are stable, thus, no code change is necessary. What do you think about removing the upper limit altogether?

**Comment by gaborbernat** [comment]
Sure, but how do you do that?

**Comment by andrask** [comment]
I'll try to remove the pluginUntilBuild property and release the new version. Based on a [thread](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010590059-Why-pluginUntilBuild-is-mandatory) this should be Ok.

**Comment by gaborbernat** [comment]
Did you do that release? THanks!

**Comment by gaborbernat** [comment]
Looking at the plugin.xml shows the change wasn't released. Old build or something? :thinking: 

```
<idea-plugin>
  <version>1.3.3</version>
  <change-notes>&lt;h3&gt;Fixed&lt;/h3&gt;
&lt;ul&gt;&lt;li&gt;[16] (&lt;a href="https://github.com/nokia/PyVenvManage/pull/18"&gt;https://github.com/nokia/PyVenvManage/pull/18&lt;/a&gt;) Upgrade gradle and support 2021.3&lt;/li&gt;&lt;/ul&gt;

&lt;h3&gt;Thanks&lt;/h3&gt;
&lt;ul&gt;&lt;li&gt;I would like to express my gratitude towards @gaborbernat for his continued support of the plugin.&lt;/li&gt;&lt;/ul&gt;</change-notes>
  <idea-version since-build="193" until-build="212.*"/>
```

**Comment by andrask** [comment]
This is weird. The 212 is only listed at the platform plugins. I'll try to fix this.

**Comment by andrask** [comment]
Looks like the patchPluginXml task somehow pulls the pluginUntil version from somewhere (I guess the published version). So it looks like not to be possible to remove the upper limit now. But we can extend it. @gaborbernat could you please try https://github.com/nokia/PyVenvManage/releases/tag/v1.3.4rc This should work all the way to 2024.1.

In the end we may choose to go for releasing once a year to keep the buzz going.

**Comment by gaborbernat** [comment]
From my sources, @YannCebron should know what's the issue here 😊 as removing the flag should definitely work per the documentation.

**Comment by YannCebron** [comment]
AFAIU you're using a very old version of gradle-intellij-plugin, please always upgrade to latest available - especially when targeting newer platform releases

`id("org.jetbrains.intellij") version "0.6.3"`

see also this page for summary of changes https://lp.jetbrains.com/gradle-intellij-plugin/

**Comment by andrask** [comment]
Excellent info, THX @YannCebron . One question: I can see that there is a `untilBuild.set` method, but is there any way to directly unset it? Or will it just remain empty with the new versions? 
It takes a little more work to update the deps and the code to work together again than just changing a few versions. At least I couldn't finish it until now. :)

**Comment by YannCebron** [comment]
There are defaults and various ways to influence the compatibility range: https://plugins.jetbrains.com/docs/intellij/gradle-guide.html#patching-the-plugin-configuration-file

It depends a bit on the API and its stability a plugin is using, but in general I'd advise to set a `xxx.*` for `until-build` and also employ Plugin Verifier to ensure binary compatiblity. If a plugin uses "open-end" compatibility, at some point we will notice it on our side and restrict `until-build` on JetBrains Marketplace. But then, problems are already in the wild.

**Comment by andrask** [comment]
I've opened #19 to cope with the upgrade. The verifier has been configured in the plugin page for a long time and runs continuously. I just have to make sure to update the versions when new platforms become available.

**Comment by gaborbernat** [comment]
Thanks!

**Pull request merged**
